-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-07-12 10:08:23 PDT
--   site:      Oracle9i
--   type:      Oracle9i



CREATE TABLE t_ant_typ (
     ant_typ_cd     INTEGER NOT NULL
    ,ant_typ_desc   TEXT
)
LOGGING;

ALTER TABLE t_ant_typ ADD CONSTRAINT t_ant_typ_pk PRIMARY KEY ( ant_typ_cd );

CREATE TABLE t_harc_add_qso_details (
    "qso_table_v007_'pk'"   INTEGER NOT NULL
    ,rptr_cd                TEXT    NOT NULL
    ,rad_typ_cd             INTEGER NOT NULL
   , pwr_typ_cd             INTEGER NOT NULL
    ,ant_typ_cd             INTEGER NOT NULL
)
LOGGING;

ALTER TABLE t_harc_add_qso_details ADD CONSTRAINT t_harc_add_qso_details_pk PRIMARY KEY ( "qso_table_v007_'pk'" );

CREATE TABLE t_harc_member (
     mem_call   TEXT  NOT NULL
    ,mem_f_nam   TEXT 
    ,mem_m_nam  TEXT 
    ,mem_l_nam  TEXT 

)
LOGGING;

ALTER TABLE t_harc_member ADD CONSTRAINT t_harc_member_pk PRIMARY KEY ( mem_call );

CREATE TABLE t_pwr_typ (
     pwr_typ_cd     INTEGER NOT NULL
    ,pwr_typ_desc   TEXT
)
LOGGING;

ALTER TABLE t_pwr_typ ADD CONSTRAINT t_pwr_typ_pk PRIMARY KEY ( pwr_typ_cd );

CREATE TABLE t_rad_typ (
     rad_typ_cd     INTEGER NOT NULL
    ,rad_typ_desc   TEXT
)
LOGGING;

ALTER TABLE t_rad_typ ADD CONSTRAINT t_rad_typ_pk PRIMARY KEY ( rad_typ_cd );

CREATE TABLE t_rpt_typ (
     rptr_cd              TEXT NOT NULL
    ,rptr_desc            TEXT
    ,rptr_call            TEXT
    ,rptr_tx_freq         REAL
    ,rptr_rx_freq         REAL
    ,rptr_ctcss           REAL
    ,rptr__lat            REAL
    ,rptr_long            REAL
    ,rptr_allstar_node    INTEGER
    ,rptr_echolink_node   INTEGER
)
LOGGING;

ALTER TABLE t_rpt_typ ADD CONSTRAINT t_rpt_typ_pk PRIMARY KEY ( rptr_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT qso_table_v007_fk FOREIGN KEY ( "qso_table_v007_'pk'" )
        REFERENCES qso_table_v007 ( "'pk'" );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_ant_typ_fk FOREIGN KEY ( ant_typ_cd )
        REFERENCES t_ant_typ ( ant_typ_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_pwr_typ_fk FOREIGN KEY ( pwr_typ_cd )
        REFERENCES t_pwr_typ ( pwr_typ_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_rad_typ_fk FOREIGN KEY ( rad_typ_cd )
        REFERENCES t_rad_typ ( rad_typ_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_rpt_cd_fk FOREIGN KEY ( rptr_cd )
        REFERENCES t_rpt_typ ( rptr_cd );


