-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-07-13 11:24:01 PDT
--   site:      Oracle9i
--   type:      Oracle9i



DROP TABLE t_ant_typ;
CREATE TABLE t_ant_typ (
    ant_typ_cd     INTEGER PRIMARY KEY NOT NULL,
    ant_typ_desc   TEXT
);

-- LOGGING

-- ALTER TABLE t_ant_typ ADD CONSTRAINT t_ant_typ_pk PRIMARY KEY ( ant_typ_cd );

DROP TABLE t_harc_add_qso_details;
CREATE TABLE t_harc_add_qso_details (
    qso_table_v007_pk  		INTEGER     PRIMARY KEY NOT NULL,
    rptr_cd                 TEXT    DEFAULT 'H2'    NOT NULL,
    rad_typ_cd              INTEGER DEFAULT 1 NOT NULL,
    pwr_typ_cd              INTEGER DEFAULT 1 NOT NULL,
    ant_typ_cd              INTEGER DEFAULT 1 NOT NULL,
    qso_comment				TEXT,
	FOREIGN KEY ( qso_table_v007_pk )
        REFERENCES qso_table_v007 ( pk ),
	FOREIGN KEY ( ant_typ_cd )
        REFERENCES t_ant_typ ( ant_typ_cd ),
	FOREIGN KEY ( pwr_typ_cd )
        REFERENCES t_pwr_typ ( pwr_typ_cd ),
	FOREIGN KEY ( rad_typ_cd )
        REFERENCES t_rad_typ ( rad_typ_cd ),
	FOREIGN KEY ( rptr_cd )
        REFERENCES t_rptr ( rptr_cd )
)
;
-- LOGGING

-- ALTER TABLE t_harc_add_qso_details ADD CONSTRAINT t_harc_add_qso_details_pk PRIMARY KEY ( "qso_table_v007_'pk'" );

DROP TABLE t_harc_member;
CREATE TABLE t_harc_member (
    mem_call    TEXT PRIMARY KEY NOT NULL,
    mem_f_nam   TEXT,
    mem_m_nam   TEXT,
    mem_l_nam   TEXT
)
;
-- LOGGING

-- ALTER TABLE t_harc_member ADD CONSTRAINT t_harc_member_pk PRIMARY KEY ( mem_call );

DROP TABLE t_pwr_typ;
CREATE TABLE t_pwr_typ (
    pwr_typ_cd     INTEGER PRIMARY KEY NOT NULL,
    pwr_typ_desc   TEXT
)
;
-- LOGGING

-- ALTER TABLE t_pwr_typ ADD CONSTRAINT t_pwr_typ_pk PRIMARY KEY ( pwr_typ_cd );

DROP TABLE t_rad_typ;
CREATE TABLE t_rad_typ (
    rad_typ_cd     INTEGER PRIMARY KEY NOT NULL,
    rad_typ_desc   TEXT
)
;
-- LOGGING

-- ALTER TABLE t_rad_typ ADD CONSTRAINT t_rad_typ_pk PRIMARY KEY ( rad_typ_cd );

DROP TABLE t_rptr;
CREATE TABLE t_rptr (
    rptr_cd              TEXT PRIMARY KEY NOT NULL,
    rptr_desc            TEXT,
    rptr_call            TEXT,
    rptr_tx_freq         REAL,
    rptr_rx_freq         REAL,
    rptr_ctcss           REAL,
    rptr__lat            REAL,
    rptr_long            REAL,
    rptr_allstar_node    INTEGER,
    rptr_echolink_node   INTEGER
)
;
-- LOGGING

-- ALTER TABLE t_rptr ADD CONSTRAINT t_rptr_typ_pk PRIMARY KEY ( rptr_cd );

/*
ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT qso_table_v007_fk FOREIGN KEY ( "qso_table_v007_'pk'" )
        REFERENCES qso_table_v007 ( "'pk'" );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_ant_typ_fk FOREIGN KEY ( ant_typ_cd )
        REFERENCES t_ant_typ ( ant_typ_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_pwr_typ_fk FOREIGN KEY ( pwr_typ_cd )
        REFERENCES t_pwr_typ ( pwr_typ_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_rad_typ_fk FOREIGN KEY ( rad_typ_cd )
        REFERENCES t_rad_typ ( rad_typ_cd );

ALTER TABLE t_harc_add_qso_details
    ADD CONSTRAINT t_rptr_typ_fk FOREIGN KEY ( rptr_cd )
        REFERENCES t_rptr ( rptr_cd );
*/

DROP VIEW v_ant_typ;
CREATE VIEW v_ant_typ  AS
	select *
	from t_ant_typ 
	;

DROP VIEW v_harc_add_qso_details;
CREATE VIEW v_harc_add_qso_details  AS
	select *
	from t_harc_add_qso_details 
	;

DROP VIEW v_harc_member;
CREATE VIEW v_harc_member  AS
	SELECT *
	FROM t_harc_member 
	;

DROP VIEW v_qso_table_v007;
CREATE VIEW v_qso_table_v007  AS
	select *
	from qso_table_v007 
	;

DROP VIEW v_reptr;
CREATE VIEW v_reptr  AS
	select * 
	from t_rptr 
	;

DROP VIEW v_member_qso;
CREATE VIEW v_member_qso  AS
	SELECT
		v_harc_member.mem_call,
    	v_harc_member.mem_f_nam,
		v_harc_member.mem_m_nam,
		v_harc_member.mem_l_nam,
		v_qso_table_v007."'band_rx'",
		v_qso_table_v007."'rx_frequency'",
		v_qso_table_v007."'tx_frequency'",
		v_qso_table_v007."'latitude'",
		v_qso_table_v007."'longitude'",
		v_qso_table_v007."'contest_id'",
		v_qso_table_v007."'qso_start'",
		v_reptr.rptr_desc
	FROM
    	v_harc_member
    		INNER JOIN v_qso_table_v007 ON v_harc_member.mem_call = v_qso_table_v007."'call'"
    		INNER JOIN v_harc_add_qso_details ON v_qso_table_v007."'pk'" = v_harc_add_qso_details."qso_table_v007_'pk'"
    		INNER JOIN v_reptr ON v_harc_add_qso_details.rptr_cd = v_reptr.rptr_cd 
	;
	
DROP VIEW v_pwr_typ;
CREATE VIEW v_pwr_typ  AS
	select *
		from t_pwr_typ 
	;

DROP VIEW v_rad_typ;
CREATE VIEW v_rad_typ  AS
	select *
	from t_rad_typ 
	;

DROP VIEW v_qso_table_expanded;
CREATE VIEW v_qso_table_expanded  AS
	SELECT
    	v_qso_table_v007.pk,
    	v_qso_table_v007.my_grid,
    	v_qso_table_v007.my_call,
    	v_qso_table_v007.my_rig,
    	v_qso_table_v007.call,
    	v_qso_table_v007.first_name,
    	v_qso_table_v007.last_name,
    	CASE
			when ifnull(v_harc_member.mem_call,'0') = '0' then 'non-member'
			else 'member'
			END as 'HARC_member',
    	v_qso_table_v007.street,
    	v_qso_table_v007.city,
    	v_qso_table_v007.county,
    	v_qso_table_v007.state,
    	v_qso_table_v007.postal_country,
    	v_qso_table_v007.zip,
    	v_qso_table_v007.grid,
    	v_qso_table_v007.dxcc_country,
    	v_qso_table_v007.email,
    	v_qso_table_v007.mode,
    	v_qso_table_v007.band_rx,
    	v_qso_table_v007.band_tx,
    	-- 
    	/***************************************
    	*                                      *
    	* ([UNIXepoch Date]/86400) + 2440587.5 *
    	*                                      *
    	***************************************/
    	datetime((((v_qso_table_v007.qso_start)/86400)+2440587.5)) as julian_qso_start,  
    	datetime(((v_qso_table_v007.qso_done)/86400)+2440587.5) as julian_qso_done,
    	-- 
    	v_qso_table_v007.latitude,
    	v_qso_table_v007.longitude,
    	v_qso_table_v007.tx_frequency,
    	v_qso_table_v007.rx_frequency,
    	v_qso_table_v007.azimuth,
    	v_qso_table_v007.elevation,
    	v_qso_table_v007.power,
    	v_qso_table_v007.dxcc_id,
    	v_qso_table_v007.contest_id,
    	v_harc_add_qso_details.qso_table_v007_pk,
    	v_harc_add_qso_details.rptr_cd,
    	v_harc_add_qso_details.rad_typ_cd,
    	v_harc_add_qso_details.pwr_typ_cd,
    	v_harc_add_qso_details.ant_typ_cd,
    	v_reptr.rptr_desc,
    	v_rad_typ.rad_typ_desc,
    	v_pwr_typ.pwr_typ_desc,
    	v_ant_typ.ant_typ_desc,
    	v_harc_add_qso_details.qso_comment
	FROM
    	v_qso_table_v007
    		INNER JOIN v_harc_add_qso_details ON v_qso_table_v007.pk = v_harc_add_qso_details.qso_table_v007_pk
    		INNER JOIN v_reptr ON v_harc_add_qso_details.rptr_cd = v_reptr.rptr_cd
    		INNER JOIN v_rad_typ ON v_harc_add_qso_details.rad_typ_cd = v_rad_typ.rad_typ_cd
    		INNER JOIN v_pwr_typ ON v_harc_add_qso_details.pwr_typ_cd = v_pwr_typ.pwr_typ_cd
    		INNER JOIN v_ant_typ ON v_harc_add_qso_details.ant_typ_cd = v_ant_typ.ant_typ_cd 
    		LEFT JOIN v_harc_member on trim(upper(call))=trim(upper(mem_call))
	;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              9
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
