CREATE TABLE t_HCOL_Mem (
    [Member#] NUMBER,
    [Roster Status] CHARACTER, 
    [First Name] CHARACTER,
    Nickname CHARACTER,
    [Last Name] CHARACTER,
    [Call Sign] CHARACTER,
    [Lic Class] CHARACTER,
    [Lic Expire Dt] DATE,
    [Lic Number] CHARACTER,
    [Lic Agency] CHARACTER,
    Address CHARACTER,
    City CHARACTER,
    State CHARACTER,
    Postal CHARACTER,
    Country CHARACTER,
    Latitude NUMBER,
    Longitude NUMBER,
    ElevationNUMBER ,
    [HCOL E-Mail Address] CHARACTER, 
    [HCOL E-Mail Status] CHARACTER,
    [Club E-Mail Address] CHARACTER,
    [Club E-Mail Status] CHARACTER,
    [Primary Phone] CHARACTER,
    [Pri Phone Type] CHARACTER,
    [Pri Publish Phone] CHARACTER,
    [Alternate Phone] CHARACTER,
    [Alt Phone Type] CHARACTER,
    [Alt Publish Phone] CHARACTER,
    [Emergency Contact] CHARACTER,
    [Join Dt] DATE,
    [Left Dt] DATE,
    [Club Rank] CHARACTER,
    [Club Position] CHARACTER,
    [Delegate Text] CHARACTER,
    [Membership Type] CHARACTER,
    [Membership Expire Dt] DATW,
    [Club Balance] NUMBEr,
    [Birth Date] DATE,
    [Private Member] CHARACTER,
    [User Timezone] CHARACTER,
    [Last Login] TIMESTAMP,
    [Role Count] Number
);
