-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-10-21 13:48:42 PDT
--   site:      Oracle9i
--   type:      Oracle9i


DROP TABLE IF EXISTS t_nco_avail;
CREATE TABLE t_nco_avail (
    pers_call TEXT NOT NULL,
    net_date DATE NOT NULL,
    scheduled TEXT NOT NULL CHECK (scheduled IN ('Y', 'N')),
    PRIMARY KEY (pers_call, net_date),
    FOREIGN KEY ( net_date ) REFERENCES t_nco_date (net_date) NOT DEFERRABLE,
     FOREIGN KEY (pers_call) REFERENCES t_nco_operator (pers_call) NOT DEFERRABLE
);


COMMENT ON COLUMN t_nco_avail.scheduled IS 'Scheduled for this date?  Yes/No (boolean)';

A

Drop table if exists t_nco_date
CREATE TABLE t_nco_date
    (
     net_date DATE  NOT NULL ,
     quarter  TEXT  NOT NULL,
    PRIMARY KEY ( net_date )
    );

DROP TABLE IF EXISTS t_nco_operator;
CREATE TABLE t_nco_operator
    (
     pers_call TEXT  NOT NULL,
     PRIMARY KEY ( pers_call ),
     FOREIGN KEY( pers_call ) REFERENCES t_pers(pers_call) NOT DEFERRABLE
    );
